# Welcome to Serverless!
#
# For full config options, check the kubeless plugin docs:
#    https://github.com/serverless/serverless-kubeless
#
# For documentation on kubeless itself:
#    http://kubeless.io

# Update the service name below with your own service name
service: smarthome-less

# Please ensure the serverless-kubeless provider plugin is installed globally.
# $ npm install -g serverless-kubeless
#
# ...before installing project dependencies to register this provider.
# $ npm install

provider:
  name: kubeless
  runtime: nodejs12
  environment:
    PGHOST: "10.96.128.38"
    PGUSER: "sa"
    PGDATABASE: "pi"
    PGPASSWORD: "sa"
    PGPORT: 5432
  package:
    exclude:
      - "test/*"
      - "src/*"
      - "node_modules/**"
plugins:
  - serverless-kubeless

functions:
  dust-current:
    handler: dust.current
    events:
      - http:
          method: get
  dust-range:
    handler: dust.range
    events:
      - http:
          method: post
          cors: true
  temperature-current:
    handler: temperature.current
    events:
      - http:
          method: get
  temperature-range:
    handler: temperature.range
    events:
      - http:
          method: post
          cors: true