kind: Deployment
apiVersion: apps/v1
metadata:
  name: aria-ui
  namespace: aria
  labels:
    k8s-app: aria-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: aria-ui
  template:
    metadata:
      name: aria-ui
      labels:
        k8s-app: aria-ui
    spec:
      containers:
        - name: aria-ui
          image: 'localhost:5000/aria-ui:0.8'
          resources:
              limits:
                memory: 512Mi
                cpu: 1
          securityContext:
            privileged: false
      initContainers:
        - name: init-frontend
          image: busybox
          command: ['sh', '-c', 'until nslookup aria-storage; do echo waiting for aria-storage; sleep 2; done;']
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
kind: Service
apiVersion: v1
metadata:
  name: aria-ui
  namespace: aria
  labels:
    k8s-app: aria-ui
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 4321
      targetPort: 4321
  selector:
    k8s-app: aria-ui
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: aria-ui
  namespace: aria
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/app-root: /
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^(/ui)$ $1/ permanent;
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    #- host: cx
     - http:
        paths:
          - path: /ui(.*)
            backend:
              serviceName: aria-ui
              servicePort: 4321