apiVersion: v1
kind: ConfigMap
metadata:
  name: smarthome-config
  namespace: smart-home
  labels:
    k8s-app: smart-home
data:
  CX_KAFKA_URL: "192.168.178.63:9092"
  CX_DB_NAME: pi
  CX_DB_USER: sa
  CX_DB_PWD: sa
  REACT_APP_API_HOSTNAME: http://192.168.178.69:32304/
